
# budget-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app
  template:
    metadata:
      labels:
        app: budget-app
    spec:
      containers:
      - name: budget-app
        image: geethgulabrathod/budjet-app_web:latest
        env:
        - name: DATABASE_URL
          value: postgres://postgres:password@postgres:5432/budget_app_development
        ports:
        - containerPort: 3000
