apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: Git repository URL
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.url) /workspace/git-repo
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: workspace
      emptyDir: {}

